name: .NET

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/DotnetDeploy.Api
    - name: Build
      run: dotnet publish src/DotnetDeploy.Api --no-restore -c Release
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Zip output
      run: zip -qq -r output.zip src/DotnetDeploy.Api/bin/Release/net6.0/publish
    - name: Upload Artifact to s3
      run: aws s3 cp src/DotnetDeploy.Api/bin/Release/net6.0/publish/*.zip s3://${{ secrets.AWS_S3_BUCKET }}/
